{{- if .Values.serviceAccount.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "api-server.fullname" . }}-controller
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
rules:
# Core resources
- apiGroups: [""]
  resources: ["namespaces", "pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Apps resources  
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Batch resources
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Forkspacer CRDs
- apiGroups: ["batch.forkspacer.com"]
  resources: ["workspaces", "workspaces/status", "workspaces/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch.forkspacer.com"]
  resources: ["modules", "modules/status", "modules/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "api-server.fullname" . }}-controller
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "api-server.fullname" . }}-controller
subjects:
- kind: ServiceAccount
  name: {{ include "api-server.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
{{- end }}