//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigItem) DeepCopyInto(out *ConfigItem) {
	*out = *in
	if in.Integer != nil {
		in, out := &in.Integer, &out.Integer
		*out = new(ConfigItemSpecInteger)
		(*in).DeepCopyInto(*out)
	}
	if in.Boolean != nil {
		in, out := &in.Boolean, &out.Boolean
		*out = new(ConfigItemSpecBoolean)
		**out = **in
	}
	if in.String != nil {
		in, out := &in.String, &out.String
		*out = new(ConfigItemSpecString)
		(*in).DeepCopyInto(*out)
	}
	if in.Option != nil {
		in, out := &in.Option, &out.Option
		*out = new(ConfigItemSpecOption)
		(*in).DeepCopyInto(*out)
	}
	if in.MultipleOptions != nil {
		in, out := &in.MultipleOptions, &out.MultipleOptions
		*out = new(ConfigItemSpecMultipleOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigItem.
func (in *ConfigItem) DeepCopy() *ConfigItem {
	if in == nil {
		return nil
	}
	out := new(ConfigItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigItemSpecBoolean) DeepCopyInto(out *ConfigItemSpecBoolean) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigItemSpecBoolean.
func (in *ConfigItemSpecBoolean) DeepCopy() *ConfigItemSpecBoolean {
	if in == nil {
		return nil
	}
	out := new(ConfigItemSpecBoolean)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigItemSpecInteger) DeepCopyInto(out *ConfigItemSpecInteger) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigItemSpecInteger.
func (in *ConfigItemSpecInteger) DeepCopy() *ConfigItemSpecInteger {
	if in == nil {
		return nil
	}
	out := new(ConfigItemSpecInteger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigItemSpecMultipleOptions) DeepCopyInto(out *ConfigItemSpecMultipleOptions) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigItemSpecMultipleOptions.
func (in *ConfigItemSpecMultipleOptions) DeepCopy() *ConfigItemSpecMultipleOptions {
	if in == nil {
		return nil
	}
	out := new(ConfigItemSpecMultipleOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigItemSpecOption) DeepCopyInto(out *ConfigItemSpecOption) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigItemSpecOption.
func (in *ConfigItemSpecOption) DeepCopy() *ConfigItemSpecOption {
	if in == nil {
		return nil
	}
	out := new(ConfigItemSpecOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigItemSpecString) DeepCopyInto(out *ConfigItemSpecString) {
	*out = *in
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigItemSpecString.
func (in *ConfigItemSpecString) DeepCopy() *ConfigItemSpecString {
	if in == nil {
		return nil
	}
	out := new(ConfigItemSpecString)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedClusterSpec) DeepCopyInto(out *ManagedClusterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedClusterSpec.
func (in *ManagedClusterSpec) DeepCopy() *ManagedClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Module) DeepCopyInto(out *Module) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ConfigItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Module.
func (in *Module) DeepCopy() *Module {
	if in == nil {
		return nil
	}
	out := new(Module)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Module) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleList) DeepCopyInto(out *ModuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Module, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleList.
func (in *ModuleList) DeepCopy() *ModuleList {
	if in == nil {
		return nil
	}
	out := new(ModuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpec) DeepCopyInto(out *ModuleSpec) {
	*out = *in
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(ModuleSpecHelm)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(ModuleSpecCustom)
		(*in).DeepCopyInto(*out)
	}
	out.Workspace = in.Workspace
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpec.
func (in *ModuleSpec) DeepCopy() *ModuleSpec {
	if in == nil {
		return nil
	}
	out := new(ModuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecCustom) DeepCopyInto(out *ModuleSpecCustom) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]CustomModulePermissionType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecCustom.
func (in *ModuleSpecCustom) DeepCopy() *ModuleSpecCustom {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecCustom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelm) DeepCopyInto(out *ModuleSpecHelm) {
	*out = *in
	if in.ExistingRelease != nil {
		in, out := &in.ExistingRelease, &out.ExistingRelease
		*out = new(ModuleSpecHelmExistingRelease)
		**out = **in
	}
	in.Chart.DeepCopyInto(&out.Chart)
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]ModuleSpecHelmValues, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]ModuleSpecHelmOutput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Cleanup = in.Cleanup
	in.Migration.DeepCopyInto(&out.Migration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelm.
func (in *ModuleSpecHelm) DeepCopy() *ModuleSpecHelm {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmChart) DeepCopyInto(out *ModuleSpecHelmChart) {
	*out = *in
	if in.Repo != nil {
		in, out := &in.Repo, &out.Repo
		*out = new(ModuleSpecHelmChartRepo)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(ModuleSpecHelmChartConfigMap)
		**out = **in
	}
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(ModuleSpecHelmChartGit)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmChart.
func (in *ModuleSpecHelmChart) DeepCopy() *ModuleSpecHelmChart {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmChart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmChartConfigMap) DeepCopyInto(out *ModuleSpecHelmChartConfigMap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmChartConfigMap.
func (in *ModuleSpecHelmChartConfigMap) DeepCopy() *ModuleSpecHelmChartConfigMap {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmChartConfigMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmChartGit) DeepCopyInto(out *ModuleSpecHelmChartGit) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(ModuleSpecHelmChartGitAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmChartGit.
func (in *ModuleSpecHelmChartGit) DeepCopy() *ModuleSpecHelmChartGit {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmChartGit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmChartGitAuth) DeepCopyInto(out *ModuleSpecHelmChartGitAuth) {
	*out = *in
	if in.HTTPSSecretRef != nil {
		in, out := &in.HTTPSSecretRef, &out.HTTPSSecretRef
		*out = new(ModuleSpecHelmChartGitAuthSecret)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmChartGitAuth.
func (in *ModuleSpecHelmChartGitAuth) DeepCopy() *ModuleSpecHelmChartGitAuth {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmChartGitAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmChartGitAuthSecret) DeepCopyInto(out *ModuleSpecHelmChartGitAuthSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmChartGitAuthSecret.
func (in *ModuleSpecHelmChartGitAuthSecret) DeepCopy() *ModuleSpecHelmChartGitAuthSecret {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmChartGitAuthSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmChartRepo) DeepCopyInto(out *ModuleSpecHelmChartRepo) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(ModuleSpecHelmChartRepoAuth)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmChartRepo.
func (in *ModuleSpecHelmChartRepo) DeepCopy() *ModuleSpecHelmChartRepo {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmChartRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmChartRepoAuth) DeepCopyInto(out *ModuleSpecHelmChartRepoAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmChartRepoAuth.
func (in *ModuleSpecHelmChartRepoAuth) DeepCopy() *ModuleSpecHelmChartRepoAuth {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmChartRepoAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmCleanup) DeepCopyInto(out *ModuleSpecHelmCleanup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmCleanup.
func (in *ModuleSpecHelmCleanup) DeepCopy() *ModuleSpecHelmCleanup {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmCleanup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmExistingRelease) DeepCopyInto(out *ModuleSpecHelmExistingRelease) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmExistingRelease.
func (in *ModuleSpecHelmExistingRelease) DeepCopy() *ModuleSpecHelmExistingRelease {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmExistingRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmMigration) DeepCopyInto(out *ModuleSpecHelmMigration) {
	*out = *in
	if in.PVCs != nil {
		in, out := &in.PVCs, &out.PVCs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmMigration.
func (in *ModuleSpecHelmMigration) DeepCopy() *ModuleSpecHelmMigration {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmOutput) DeepCopyInto(out *ModuleSpecHelmOutput) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ModuleSpecHelmOutputValueFrom)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmOutput.
func (in *ModuleSpecHelmOutput) DeepCopy() *ModuleSpecHelmOutput {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmOutputValueFrom) DeepCopyInto(out *ModuleSpecHelmOutputValueFrom) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(ModuleSpecHelmOutputValueFromSecret)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmOutputValueFrom.
func (in *ModuleSpecHelmOutputValueFrom) DeepCopy() *ModuleSpecHelmOutputValueFrom {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmOutputValueFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmOutputValueFromSecret) DeepCopyInto(out *ModuleSpecHelmOutputValueFromSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmOutputValueFromSecret.
func (in *ModuleSpecHelmOutputValueFromSecret) DeepCopy() *ModuleSpecHelmOutputValueFromSecret {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmOutputValueFromSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmValues) DeepCopyInto(out *ModuleSpecHelmValues) {
	*out = *in
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(string)
		**out = **in
	}
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(ModuleSpecHelmValuesConfigMap)
		**out = **in
	}
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmValues.
func (in *ModuleSpecHelmValues) DeepCopy() *ModuleSpecHelmValues {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpecHelmValuesConfigMap) DeepCopyInto(out *ModuleSpecHelmValuesConfigMap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpecHelmValuesConfigMap.
func (in *ModuleSpecHelmValuesConfigMap) DeepCopy() *ModuleSpecHelmValuesConfigMap {
	if in == nil {
		return nil
	}
	out := new(ModuleSpecHelmValuesConfigMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleStatus) DeepCopyInto(out *ModuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastActivity != nil {
		in, out := &in.LastActivity, &out.LastActivity
		*out = (*in).DeepCopy()
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleStatus.
func (in *ModuleStatus) DeepCopy() *ModuleStatus {
	if in == nil {
		return nil
	}
	out := new(ModuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleWorkspaceReference) DeepCopyInto(out *ModuleWorkspaceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleWorkspaceReference.
func (in *ModuleWorkspaceReference) DeepCopy() *ModuleWorkspaceReference {
	if in == nil {
		return nil
	}
	out := new(ModuleWorkspaceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workspace) DeepCopyInto(out *Workspace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workspace.
func (in *Workspace) DeepCopy() *Workspace {
	if in == nil {
		return nil
	}
	out := new(Workspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Workspace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceAutoHibernation) DeepCopyInto(out *WorkspaceAutoHibernation) {
	*out = *in
	if in.WakeSchedule != nil {
		in, out := &in.WakeSchedule, &out.WakeSchedule
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceAutoHibernation.
func (in *WorkspaceAutoHibernation) DeepCopy() *WorkspaceAutoHibernation {
	if in == nil {
		return nil
	}
	out := new(WorkspaceAutoHibernation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceConnection) DeepCopyInto(out *WorkspaceConnection) {
	*out = *in
	if in.SecretReference != nil {
		in, out := &in.SecretReference, &out.SecretReference
		*out = new(WorkspaceConnectionSecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceConnection.
func (in *WorkspaceConnection) DeepCopy() *WorkspaceConnection {
	if in == nil {
		return nil
	}
	out := new(WorkspaceConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceConnectionSecretReference) DeepCopyInto(out *WorkspaceConnectionSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceConnectionSecretReference.
func (in *WorkspaceConnectionSecretReference) DeepCopy() *WorkspaceConnectionSecretReference {
	if in == nil {
		return nil
	}
	out := new(WorkspaceConnectionSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceFromReference) DeepCopyInto(out *WorkspaceFromReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceFromReference.
func (in *WorkspaceFromReference) DeepCopy() *WorkspaceFromReference {
	if in == nil {
		return nil
	}
	out := new(WorkspaceFromReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceList) DeepCopyInto(out *WorkspaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Workspace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceList.
func (in *WorkspaceList) DeepCopy() *WorkspaceList {
	if in == nil {
		return nil
	}
	out := new(WorkspaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkspaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSpec) DeepCopyInto(out *WorkspaceSpec) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(WorkspaceFromReference)
		**out = **in
	}
	in.Connection.DeepCopyInto(&out.Connection)
	if in.ManagedCluster != nil {
		in, out := &in.ManagedCluster, &out.ManagedCluster
		*out = new(ManagedClusterSpec)
		**out = **in
	}
	if in.AutoHibernation != nil {
		in, out := &in.AutoHibernation, &out.AutoHibernation
		*out = new(WorkspaceAutoHibernation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSpec.
func (in *WorkspaceSpec) DeepCopy() *WorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceStatus) DeepCopyInto(out *WorkspaceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastActivity != nil {
		in, out := &in.LastActivity, &out.LastActivity
		*out = (*in).DeepCopy()
	}
	if in.HibernatedAt != nil {
		in, out := &in.HibernatedAt, &out.HibernatedAt
		*out = (*in).DeepCopy()
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceStatus.
func (in *WorkspaceStatus) DeepCopy() *WorkspaceStatus {
	if in == nil {
		return nil
	}
	out := new(WorkspaceStatus)
	in.DeepCopyInto(out)
	return out
}
