---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-batch-environment-sh-v1-module
  failurePolicy: Fail
  name: mmodule-v1.kb.io
  rules:
  - apiGroups:
    - batch.forkspacer.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - modules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-batch-environment-sh-v1-workspace
  failurePolicy: Fail
  name: mworkspace-v1.kb.io
  rules:
  - apiGroups:
    - batch.forkspacer.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspaces
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-batch-environment-sh-v1-module
  failurePolicy: Fail
  name: vmodule-v1.kb.io
  rules:
  - apiGroups:
    - batch.forkspacer.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - modules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-batch-environment-sh-v1-workspace
  failurePolicy: Fail
  name: vworkspace-v1.kb.io
  rules:
  - apiGroups:
    - batch.forkspacer.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspaces
  sideEffects: None
