apiVersion: batch.forkspacer.com/v1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: workspace-sample
spec:
  # TODO(user): Add fields here
