apiVersion: batch.forkspacer.com/v1
kind: Module
metadata:
  name: vcluster-nginx
  namespace: default
spec:
  source:
    raw:
      kind: Helm
      metadata:
        name: nginx
        version: "1.0.0"
        supportedOperatorVersion: ">= 0.0.0, < 1.0.0"
        author: "platform-team"
        description: "Nginx web server deployed to vcluster"
        category: "web"
        resource_usage:
          cpu: "100m"
          memory: "128Mi"

      config:
        - type: integer
          name: "Replica Count"
          alias: "replicaCount"
          spec:
            editable: true
            required: false
            default: 1
            min: 1
            max: 3

      spec:
        namespace: default
        repo: https://charts.bitnami.com/bitnami
        chartName: nginx
        version: "22.0.10"

        values:
          - raw:
              replicaCount: "{{.config.replicaCount}}"
              service:
                type: ClusterIP

        outputs:
          - name: "Nginx Service"
            value: "vcluster-nginx.default.svc.cluster.local"
          - name: "HTTP Port"
            value: 80

        cleanup:
          removeNamespace: false
          removePVCs: false

  workspace:
    name: vcluster
    namespace: default

  config:
    replicaCount: 1

  hibernated: false