apiVersion: batch.forkspacer.com/v1
kind: Module
metadata:
  name: custom
  namespace: default
spec:
  source:
    raw:
      kind: Custom
      metadata:
        name: test
        version: "1.0.0"
        supportedOperatorVersion: ">= 0.0.0, < 1.0.0"
        author: "platform-team"
        description: "Test"
        category: "database"
        resource_usage:
          cpu: "200m"
          memory: "256Mi"

      config:
        - type: option
          name: "Version"
          alias: "version"
          spec:
            editable: true
            required: false
            default: "21.2.9"
            values:
              - "21.2.9"
              - "21.2.7"
              - "21.2.6"

        - type: integer
          name: "Replica Count"
          alias: "replicaCount"
          spec:
            editable: true
            required: false
            default: 1
            min: 0
            max: 5

      spec:
        repo:
          file: "https://ftp.aykhans.me/web/client/pubshares/hB6VSdCnBCr8gFPeiMuCji/browse?path=/plugin.so"

  workspace:
    name: default
    namespace: default
  config:
    version: 21.2.7
    replicaCount: 0
