apiVersion: batch.forkspacer.com/v1
kind: Module
metadata:
  name: custom
  namespace: default
spec:
  source:
    raw:
      kind: Custom
      metadata:
        name: test
        supportedOperatorVersion: ">= 0.0.0, < 1.0.0"
      spec:
        image: "ghcr.io/forkspacer/custom-example:latest"
        permissions:
          - "workspace"
          - "controller"

  workspace:
    name: default
    namespace: default
