apiVersion: batch.forkspacer.com/v1
kind: Module
metadata:
  name: redis
  namespace: default
spec:
  source:
    existingHelmRelease:
      name: redis
      chartSource:
        repository:
          url: https://charts.bitnami.com/bitnami
          chart: redis
          version: "21.2.9"

  workspace:
    name: default
    # namespace: default
