apiVersion: batch.forkspacer.com/v1
kind: Workspace
metadata:
  name: default
  namespace: default

spec: {}
  # type: kubernetes
  # connection:
  #   type: kubeconfig
  #   secretReference:
  #     name: vcluster-kube
  #     namespace: default
  # hibernated: false
  # autoHibernation:
  #   enabled: false
  #   schedule: "0 42 18 * * *"
  #   wakeSchedule: "0 44 18 * * *"
