apiVersion: batch.forkspacer.com/v1
kind: Workspace
metadata:
  name: vcluster
  namespace: default

spec:
  type: kubernetes
  hibernated: false
  connection:
    type: kubeconfig
    secretReference:
      name: vcluster-kubeconfig
      namespace: default
  # autoHibernation:
  #   enabled: false
  #   schedule: "0 0 18 * * *"      # Hibernate at 6 PM daily
  #   wakeSchedule: "0 0 8 * * *"   # Wake at 8 AM daily
