replicaCount: 1

# Image configuration - will be overridden by global values from parent chart
image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 8080
  targetPort: 8421
  # nodePort: 30421  # Only used when type is NodePort

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  API_PORT: "8421"
  DEV: "false"

livenessProbe:
  httpGet:
    path: /api/v1/docs
    port: 8421
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /api/v1/docs
    port: 8421
  initialDelaySeconds: 5
  periodSeconds: 5

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}

# Ingress is handled by the parent chart with unified routing
# The parent chart routes /api/* to this service