apiVersion: v2
name: forkspacer
description: A Kubernetes operator for dynamic workspace lifecycle management
type: application
version: 0.1.5
appVersion: "v0.1.5"
keywords:
  - operator
  - workspace
  - kubernetes
  - forkspacer
home: https://github.com/forkspacer/forkspacer
sources:
  - https://github.com/forkspacer/forkspacer
maintainers:
  - name: Forkspacer Team
    email: team@forkspacer.com
dependencies:
  - name: api-server
    version: "1.0.0"
    repository: "file://./charts/api-server"
    condition: apiServer.enabled
  - name: operator-ui
    version: "0.1.1"
    repository: "file://./charts/operator-ui"
    condition: operatorUI.enabled