{{- if .Values.webhook.enable }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: operator-mutating-webhook-configuration
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.certmanager.enable }}
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/serving-cert"
    {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
webhooks:
  - name: mmodule-v1.kb.io
    clientConfig:
      service:
        name: operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-batch-forkspacer-com-v1-module
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - batch.forkspacer.com
        apiVersions:
          - v1
        resources:
          - modules
  - name: mworkspace-v1.kb.io
    clientConfig:
      service:
        name: operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-batch-forkspacer-com-v1-workspace
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - batch.forkspacer.com
        apiVersions:
          - v1
        resources:
          - workspaces
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: operator-validating-webhook-configuration
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.certmanager.enable }}
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/serving-cert"
    {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
webhooks:
  - name: vmodule-v1.kb.io
    clientConfig:
      service:
        name: operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-batch-forkspacer-com-v1-module
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - batch.forkspacer.com
        apiVersions:
          - v1
        resources:
          - modules
  - name: vworkspace-v1.kb.io
    clientConfig:
      service:
        name: operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-batch-forkspacer-com-v1-workspace
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - batch.forkspacer.com
        apiVersions:
          - v1
        resources:
          - workspaces
{{- end }}
