name: Update Dependencies

on:
  repository_dispatch:
    types: [dependency-update]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Extract component info
        id: component
        run: |
          echo "component=${{ github.event.client_payload.component }}" >> $GITHUB_OUTPUT
          echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT
          echo "chart_version=${{ github.event.client_payload.chart_version }}" >> $GITHUB_OUTPUT

      - name: Update Chart.yaml dependency
        if: ${{ steps.component.outputs.component != 'forkspacer' }}
        run: |
          make update-dependency \
            COMPONENT="${{ steps.component.outputs.component }}" \
            VERSION="${{ steps.component.outputs.version }}" \
            CHART_VERSION="${{ steps.component.outputs.chart_version }}"

      - name: Update forkspacer version
        if: ${{ steps.component.outputs.component == 'forkspacer' }}
        run: |
          make update-forkspacer-version VERSION="${{ steps.component.outputs.version }}"

      - name: Install Kubebuilder
        if: ${{ steps.component.outputs.component == 'forkspacer' }}
        run: |
          curl -L -o kubebuilder "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v4.9.0/kubebuilder_linux_amd64"
          chmod +x kubebuilder
          sudo mv kubebuilder /usr/local/bin/
          kubebuilder version

      - name: Update install.yaml
        if: ${{ steps.component.outputs.component == 'forkspacer' }}
        run: |
          make build-installer IMG=ghcr.io/forkspacer/forkspacer:${{ steps.component.outputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.DEPENDENCY_UPDATE_TOKEN }}
          commit-message: |
            feat: update ${{ steps.component.outputs.component }} to ${{ steps.component.outputs.version }}
            
            ${{ steps.component.outputs.component == 'forkspacer' && '- Updated helm chart version to ' || '- Updated dependency version to ' }}${{ steps.component.outputs.chart_version }} in Chart.yaml
            - Updated image tag to ${{ steps.component.outputs.version }} in values.yaml
            ${{ steps.component.outputs.component == 'forkspacer' && '- Updated Makefile VERSION to ' || '' }}${{ steps.component.outputs.component == 'forkspacer' && steps.component.outputs.version || '' }}
            ${{ steps.component.outputs.component == 'forkspacer' && '- Updated dist/install.yaml with new manifests' || '' }}
            
          title: "feat: update ${{ steps.component.outputs.component }} to ${{ steps.component.outputs.version }}"
          body: |
            ## 🔄 ${{ steps.component.outputs.component == 'forkspacer' && 'Main Chart Version' || 'Dependency' }} Update
            
            This PR automatically updates the **${{ steps.component.outputs.component }}** ${{ steps.component.outputs.component == 'forkspacer' && 'main chart version' || 'dependency' }}.
            
            ### Changes
            - **Component**: ${{ steps.component.outputs.component }}
            - **New Version**: ${{ steps.component.outputs.version }}
            - **Chart Version**: ${{ steps.component.outputs.chart_version }}
            - **Updated**: helm/Chart.yaml ${{ steps.component.outputs.component == 'forkspacer' && 'version and appVersion' || 'dependency version' }}
            - **Updated**: helm/values.yaml image tag${{ steps.component.outputs.component == 'forkspacer' && '\n            - **Updated**: Makefile VERSION variable' || '' }}${{ steps.component.outputs.component == 'forkspacer' && '\n            - **Updated**: dist/install.yaml with new manifests' || '' }}
            
            ### Triggered by
            - Repository: forkspacer/${{ steps.component.outputs.component }}
            - Tag: ${{ steps.component.outputs.version }}
            - Release workflow
            
            ### Verification
            - [ ] Chart.yaml ${{ steps.component.outputs.component == 'forkspacer' && 'version and appVersion' || 'dependency version' }} updated correctly
            - [ ] values.yaml image tag updated correctly${{ steps.component.outputs.component == 'forkspacer' && '\n            - [ ] Makefile VERSION variable updated correctly' || '' }}${{ steps.component.outputs.component == 'forkspacer' && '\n            - [ ] dist/install.yaml regenerated with updated manifests' || '' }}
            - [ ] No additional files committed (Chart.lock, .tgz files excluded)
            
          branch: dependency-update/${{ steps.component.outputs.component }}-${{ steps.component.outputs.chart_version }}
          delete-branch: true

      - name: Summary
        run: |
          make dependency-summary \
            COMPONENT="${{ steps.component.outputs.component }}" \
            VERSION="${{ steps.component.outputs.version }}" \
            CHART_VERSION="${{ steps.component.outputs.chart_version }}"

      - name: Trigger Helm Pages Deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DEPENDENCY_UPDATE_TOKEN }}
          event-type: helm-pages-deploy
          client-payload: |
            {
              "component": "${{ steps.component.outputs.component }}",
              "version": "${{ steps.component.outputs.version }}",
              "chart_version": "${{ steps.component.outputs.chart_version }}"
            }